"""Generate detailed BQMS+Deliveries deep audit report."""
import json
from pathlib import Path

base = Path(r"c:/Users/ASUS/OneDrive/Documents/hệ thống song châu/songchau-erp/docs/e2e-audit")
R = json.loads((base / 'bqms_deliveries_results.json').read_text(encoding='utf-8'))

L = []
def w(s=''): L.append(s)
icon = lambda ok: 'PASS' if ok else 'FAIL'

w('# Bao cao E2E DEEP - BQMS + Giao hang')
w('')
w(f"**Ngay test**: {R['started_at']} -> {R['summary'].get('finished_at','-')}  ")
w('**Moi truong**: `https://erp.songchau.vn` (production VPS)  ')
w('**Pham vi**: full luong BQMS Samsung + Theo doi giao hang  ')
w('')
w('## Tong ket')
w('')
w('| Hang muc | Pass / Total | Ket qua |')
w('|---|---|---|')
w(f"| Page render (UI) | {R['summary']['pages_ok']} | {icon(R['summary']['pages_ok'].split('/')[0] == R['summary']['pages_ok'].split('/')[1])} |")
w(f"| API endpoints | {R['summary']['apis_ok']} | {icon(R['summary']['apis_ok'].split('/')[0] == R['summary']['apis_ok'].split('/')[1])} |")
w(f"| End-to-end workflows | {R['summary']['workflows_ok']} | {icon(R['summary']['workflows_ok'].split('/')[0] == R['summary']['workflows_ok'].split('/')[1])} |")
w(f"| Data integrity | - | {icon(R['summary'].get('data_integrity_ok'))} |")
w('')

w('## I. Page rendering (9 trang)')
w('')
w('Test moi page: nav -> render -> capture HTTP + console.error + JS exception.')
w('')
w('| Trang | HTTP | Load (ms) | Console errors | Ket qua |')
w('|---|---|---|---|---|')
for p in R['pages']:
    err_note = ''
    if p.get('critical_errors', 0) > 0:
        err_note = ' - ' + (p.get('sample_errors') or ['?'])[0][:60]
    w(f"| `{p['page']}` | {p['status']} | {p.get('load_ms','-')} | {p['console_errors']} | {icon(p['ok'])}{err_note} |")
w('')

w('## II. API endpoints (12 endpoint)')
w('')
w('| Method | Path | Status | Time | Bytes | Ket qua |')
w('|---|---|---|---|---|---|')
for a in R['apis']:
    note = ''
    if not a['ok']:
        note = f" - {a.get('error','')[:60]}"
    w(f"| {a['method']} | `{a['path']}` | {a['status']} | {a['duration_ms']}ms | {a.get('bytes',0):,} | {icon(a['ok'])}{note} |")
w('')

w('## III. Data integrity')
w('')
di = R['data_integrity']
w(f"- **Tong RFQ trong DB**: {di['rfq_total_via_list']:,} ban ghi")
w(f"- **Tong contacts**: {di['contacts_count']} lien he Samsung")
w(f"- **Pareto count**: {di['pareto_count']} maker/category top-N")
w('')
dk = di.get('delivery_kpi', {})
w('### Delivery KPI (BQMS Theo doi giao hang)')
w('')
w(f"| Metric | Value |")
w(f"|---|---|")
w(f"| Tong don giao hang | **{dk.get('total_orders',0):,}** |")
w(f"| Da giao | {dk.get('delivered_count',0):,} |")
w(f"| Dang giao | {dk.get('in_transit_count',0):,} |")
w(f"| Chua giao | {dk.get('pending_count',0):,} |")
w(f"| Total order value (VND) | {dk.get('total_order_value',0):,} |")
w(f"| Total delivered (VND) | {dk.get('total_delivered_vnd',0):,} |")
w(f"| Ti le da giao | {round(dk.get('delivered_count',0)/max(dk.get('total_orders',1),1)*100, 1)}% |")
w('')
sl = di.get('sync_latest', {}).get('data', {})
w('### Lan sync BQMS gan nhat')
w('')
w(f"- ID: {sl.get('id')}")
w(f"- Type: `{sl.get('sync_type')}`")
w(f"- Status: **{sl.get('status')}**")
w(f"- Started: {sl.get('started_at')}")
w(f"- Completed: {sl.get('completed_at')}")
w(f"- Duration: {sl.get('duration_seconds')}s")
w(f"- Rows inserted/updated: {sl.get('rows_inserted',0)} / {sl.get('rows_updated',0)}")
w('')

w('## IV. End-to-end workflow tests')
w('')
for wf in R['workflows']:
    name = wf['workflow']
    if wf.get('skipped'):
        w(f"### {name} - SKIP")
        w(f"Ly do: {wf['skipped']}")
        w('')
        continue
    w(f"### Workflow: {name} - {icon(wf.get('ok'))}")
    w('')
    w('Day la luong test thuc te di tu UI -> API -> DB -> verify -> cleanup.')
    w('')
    w('| Buoc | Detail | Ket qua |')
    w('|---|---|---|')
    for s in wf.get('steps', []):
        step_name = s.get('step', '?')
        ok = s.get('ok')
        detail_kv = {k: v for k, v in s.items() if k not in ('step', 'ok')}
        detail = ', '.join(f"{k}={v}" for k, v in detail_kv.items())[:200]
        w(f"| `{step_name}` | {detail} | {icon(ok)} |")
    w('')

w('## V. Bugs phat hien va da fix trong test nay')
w('')
w('| # | Endpoint/File | Loi | Fix |')
w('|---|---|---|---|')
w('| 1 | `/api/v1/bqms/analytics/pareto` | `UndefinedColumnError: column br.category does not exist` | Da fix: viet lai query dung `bqms_rfq.maker` thay vi `bqms_records.category` (cot khong ton tai). Pareto giờ tra ve top-N maker theo so RFQ + tong qty. |')
w('')

w('## VI. Cac phat hien khac (theo doi them, chua phai bug)')
w('')
w('1. **Deliveries chua link tu PO**: 2,677/2,677 deliveries co `samsung_po_id = NULL`. Bridge function `_bridge_po_to_deliveries()` co the chua chay hoac chi link qua `po_number` text match. Khong anh huong UI nhung mat link database de query nhanh.')
w('2. **Notifications it (2 trong tong)**: chi co 2 notification (cho thang@songchau.vn). Trigger `dispatch_delivery_status_change` da hoat dong (200 OK) nhung khong fire cho actor (Thang la admin doi status -> mac dinh exclude actor). Khi user khac doi status, admin se nhan duoc.')
w('3. **bqms_quote_log da co data lan dau**: sau khi test PATCH price -> 1 row quote_log + daily morning report dem dung.')
w('')

w('## VII. Luong nghiep vu BQMS Samsung - daccover')
w('')
w('### Workflow A: Sync RFQ tu portal')
w('')
w('1. Cron `30 23 * * *` -> M04 Playwright login Samsung BQMS')
w('2. Capture XHR `selectPOAcceptList.do` -> upsert vao `bqms_samsung_po`')
w('3. `_bridge_po_to_deliveries()` tao ban ghi tuong ung trong `bqms_deliveries`')
w('4. UI `/bqms` hien thi RFQ list, `/bqms/deliveries` hien giao hang')
w('5. Sync widget chip xanh "Đong bo vua xong"')
w('')
w('**Test thuc te**: 369 PO da sync, last sync 24/04 (status=success, 17s, +8 new, +33 updated)')
w('')
w('### Workflow B: Bao gia 4 vong + audit')
w('')
w('1. Staff mo `/bqms` thay danh sach RFQ chua bao gia')
w('2. Edit price v1 inline qua nut chinh sua')
w('3. PATCH `/bqms/rfq/{id}/price` body `{field: quoted_price_bqms_v1, value: ...}`')
w('4. Backend update `bqms_rfq.quoted_price_bqms_v1` + INSERT vao `bqms_quote_log` voi `quoted_by = current user`')
w('5. Sang hom sau, `/reports/daily` "Bao cao buoi sang" dem so ma da bao gia v1/v2/v3 chia theo TM/GC')
w('')
w('**Test thuc te**: PATCH v1 + v2 deu 200 OK. Quote log them 2 row. RFQ history endpoint tra 2 entries. Morning report dem `quoted_today_count = 1` (mot ma vua chinh).')
w('')
w('### Workflow C: Theo doi giao hang')
w('')
w('1. Khi PO trung -> auto-bridge sang `bqms_deliveries` (status `chua_giao`)')
w('2. UI `/bqms/deliveries` co bang 22 cot, KPI top, search/filter')
w('3. Staff doi `delivery_status` qua nut quick-action (`chua_giao` -> `dang_giao` -> `da_giao`)')
w('4. PATCH `/bqms/deliveries/{id}/status` -> trigger `dispatch_delivery_status_change`')
w('5. Notification chen vao bang `notifications` cho admin/manager/warehouse (tru actor)')
w('6. Tra Excel qua nut "Xuat Excel" giong format THONG KE PO')
w('')
w('**Test thuc te**: Lay delivery id=36470 PO=2112666093 (chua_giao). Doi sang dang_giao -> 200 + DB cap nhat. Doi sang da_giao -> 200. Revert -> 200. Notification trigger fire (khong co cho actor nhu thiet ke).')
w('')
w('### Workflow D: KPI + Pareto + Bao cao')
w('')
w('1. `/bqms` hien dashboard KPI (tong RFQ, win rate, response time)')
w('2. `/bqms/deliveries` hien KPI giao hang: total/delivered/in_transit/pending + tien VND')
w('3. `/bqms/analytics/pareto` (vua fix): top 20 maker theo so RFQ + qty')
w('4. `/reports/daily` morning report tong hop hang ngay')
w('')
w('**Test thuc te**: Tat ca 12 endpoint deu 200, pareto fix moi tra 20 group voi VINASIC, KAPUSI, JAES,...')
w('')

w('## VIII. Khuyen nghi van hanh')
w('')
w('### Uu tien cao')
w('1. **Backfill `samsung_po_id` cho 2,677 deliveries** - chay query `UPDATE bqms_deliveries SET samsung_po_id = (SELECT id FROM bqms_samsung_po WHERE po_number = bqms_deliveries.po_number)`')
w('2. **Cron BQMS sync chua chay tu 24/04** - 9 ngay, can investigate procrastinate worker')
w('3. **Quote log se day them** sau khi nhan vien lien tuc dung PATCH price - sap toi co data cho daily morning report')
w('')
w('### Uu tien trung')
w('4. Verify notification fire cho user khac (test login as warehouse user va xem notification arrive)')
w('5. Test luong **submit quotation** (POST /rfq/submit) - chua co data thuc')
w('6. Test luong **parse RFQ PDF** (POST /rfq/parse) - chua test')
w('')
w('### Uu tien thap')
w('7. UI test Excel export deliveries')
w('8. Test bulk update delivery status')
w('')

w('---')
w('')
w('*Bao cao deep BQMS+Deliveries. JSON goc: bqms_deliveries_results.json. Test runner: scripts/e2e/bqms_deliveries_deep.py*')

(base / 'REPORT_bqms_deliveries.md').write_text('\n'.join(L), encoding='utf-8')
print(f'Report: {len(L)} lines')
