"""Purchase Orders API — list, create, update, submit, receive."""

from __future__ import annotations

from datetime import date
from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel
import asyncpg

from app.core.database import get_db
from app.core.rbac import require_role
from app.core.security import TokenData
from app.services.workflow_engine import (
    create_workflow,
    execute_action,
    WFAction,
)

router = APIRouter()


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------

class POLineItem(BaseModel):
    product_id: str
    quantity: float
    unit: str = "cái"
    unit_price: float
    note: str | None = None


class POCreateRequest(BaseModel):
    supplier_id: str
    expected_date: date | None = None
    notes: str | None = None
    line_items: list[POLineItem]


class POUpdateRequest(BaseModel):
    supplier_id: str | None = None
    expected_date: date | None = None
    notes: str | None = None
    line_items: list[POLineItem] | None = None


class ReceiveLineItem(BaseModel):
    po_line_id: str
    quantity_received: float
    note: str | None = None


class POReceiveRequest(BaseModel):
    received_items: list[ReceiveLineItem]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

async def _get_po(conn: asyncpg.Connection, po_id: str) -> dict:
    row = await conn.fetchrow(
        "SELECT * FROM purchase_orders WHERE id = $1", po_id
    )
    if not row:
        raise HTTPException(status_code=404, detail="Đơn mua hàng không tồn tại")
    return dict(row)


async def _get_po_lines(conn: asyncpg.Connection, po_id: str) -> list[dict]:
    rows = await conn.fetch(
        """
        SELECT pol.*, p.product_name, p.bqms_code
        FROM po_line_items pol
        LEFT JOIN products p ON p.id = pol.product_id
        WHERE pol.po_id = $1
        ORDER BY pol.line_number ASC
        """,
        po_id,
    )
    return [dict(r) for r in rows]


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("")
async def list_purchase_orders(
    status: str | None = Query(None),
    supplier_id: int | None = Query(None),
    date_from: date | None = Query(None),
    date_to: date | None = Query(None),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    token_data: TokenData = Depends(require_role("staff", "manager", "admin")),
    conn: asyncpg.Connection = Depends(get_db),
):
    conditions = ["1=1"]
    params: list = []
    idx = 1

    if status:
        conditions.append(f"po.status = ${idx}")
        params.append(status)
        idx += 1
    if supplier_id:
        conditions.append(f"po.supplier_id = ${idx}")
        params.append(supplier_id)
        idx += 1
    if date_from:
        conditions.append(f"po.created_at::date >= ${idx}")
        params.append(date_from)
        idx += 1
    if date_to:
        conditions.append(f"po.created_at::date <= ${idx}")
        params.append(date_to)
        idx += 1

    where = " AND ".join(conditions)

    total = await conn.fetchval(
        f"SELECT COUNT(*) FROM purchase_orders po WHERE {where}", *params
    )

    params.extend([limit, offset])
    rows = await conn.fetch(
        f"""
        SELECT po.*, s.name AS supplier_name, u.full_name AS creator_name
        FROM purchase_orders po
        LEFT JOIN suppliers s ON s.id = po.supplier_id
        LEFT JOIN users u ON u.id = po.created_by
        WHERE {where}
        ORDER BY po.created_at DESC
        LIMIT ${idx} OFFSET ${idx + 1}
        """,
        *params,
    )
    return {"data": [dict(r) for r in rows], "total": total}


@router.post("", status_code=201)
async def create_purchase_order(
    body: POCreateRequest,
    token_data: TokenData = Depends(require_role("staff", "manager", "admin")),
    conn: asyncpg.Connection = Depends(get_db),
):
    if not body.line_items:
        raise HTTPException(status_code=400, detail="Đơn hàng phải có ít nhất 1 dòng")

    total_amount = sum(li.quantity * li.unit_price for li in body.line_items)

    async with conn.transaction():
        # PO number generated by DB trigger
        po = await conn.fetchrow(
            """
            INSERT INTO purchase_orders
                (supplier_id, expected_date, notes, total_amount, created_by)
            VALUES ($1, $2, $3, $4, $5::uuid)
            RETURNING *
            """,
            body.supplier_id,
            body.expected_date,
            body.notes,
            total_amount,
            token_data.user_id,
        )
        po_id = str(po["id"])

        for i, li in enumerate(body.line_items, start=1):
            await conn.execute(
                """
                INSERT INTO po_line_items
                    (po_id, product_id, quantity, unit, unit_price, line_total, line_number, note)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
                """,
                po_id,
                li.product_id,
                li.quantity,
                li.unit,
                li.unit_price,
                li.quantity * li.unit_price,
                i,
                li.note,
            )

    return {"data": dict(po)}


@router.get("/{po_id}")
async def get_purchase_order(
    po_id: str,
    token_data: TokenData = Depends(require_role("staff", "manager", "admin")),
    conn: asyncpg.Connection = Depends(get_db),
):
    po = await _get_po(conn, po_id)
    lines = await _get_po_lines(conn, po_id)

    # Get supplier info
    supplier = await conn.fetchrow(
        "SELECT id, name, tax_code, contact_phone, email FROM suppliers WHERE id = $1",
        po.get("supplier_id"),
    )

    po["line_items"] = lines
    po["supplier"] = dict(supplier) if supplier else None
    return {"data": po}


@router.put("/{po_id}")
async def update_purchase_order(
    po_id: str,
    body: POUpdateRequest,
    token_data: TokenData = Depends(require_role("staff", "manager", "admin")),
    conn: asyncpg.Connection = Depends(get_db),
):
    po = await _get_po(conn, po_id)
    if po["status"] != "draft":
        raise HTTPException(
            status_code=400,
            detail="Chỉ có thể sửa đơn hàng ở trạng thái nháp (draft)",
        )

    async with conn.transaction():
        # Update header fields
        updates = {}
        if body.supplier_id is not None:
            updates["supplier_id"] = body.supplier_id
        if body.expected_date is not None:
            updates["expected_date"] = body.expected_date
        if body.notes is not None:
            updates["notes"] = body.notes

        if body.line_items is not None:
            total_amount = sum(li.quantity * li.unit_price for li in body.line_items)
            updates["total_amount"] = total_amount

            # Replace all line items
            await conn.execute(
                "DELETE FROM po_line_items WHERE po_id = $1", po_id
            )
            for i, li in enumerate(body.line_items, start=1):
                await conn.execute(
                    """
                    INSERT INTO po_line_items
                        (po_id, product_id, quantity, unit, unit_price, line_total, line_number, note)
                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
                    """,
                    po_id,
                    li.product_id,
                    li.quantity,
                    li.unit,
                    li.unit_price,
                    li.quantity * li.unit_price,
                    i,
                    li.note,
                )

        if updates:
            set_parts = []
            values: list = []
            for i, (col, val) in enumerate(updates.items(), start=1):
                set_parts.append(f"{col} = ${i}")
                values.append(val)
            values.append(po_id)
            row = await conn.fetchrow(
                f"UPDATE purchase_orders SET {', '.join(set_parts)}, updated_at = NOW() "
                f"WHERE id = ${len(values)} RETURNING *",
                *values,
            )
        else:
            row = await conn.fetchrow(
                "SELECT * FROM purchase_orders WHERE id = $1", po_id
            )

    return {"data": dict(row)}


@router.post("/{po_id}/submit")
async def submit_purchase_order(
    po_id: str,
    token_data: TokenData = Depends(require_role("staff", "manager", "admin")),
    conn: asyncpg.Connection = Depends(get_db),
):
    """Submit a draft PO for approval — creates a workflow and transitions it."""
    po = await _get_po(conn, po_id)
    if po["status"] != "draft":
        raise HTTPException(
            status_code=400,
            detail="Chỉ có thể gửi duyệt đơn hàng ở trạng thái nháp (draft)",
        )

    total = float(po.get("total_amount") or 0)

    async with conn.transaction():
        # Update PO status
        await conn.execute(
            "UPDATE purchase_orders SET status = 'pending_approval', updated_at = NOW() WHERE id = $1",
            po_id,
        )

        # Create workflow in draft then immediately submit
        wf = await create_workflow(
            conn,
            entity_type="purchase_order",
            entity_id=po_id,
            amount=total,
            created_by=token_data.user_id,
            title=f"Phê duyệt PO {po.get('po_number', po_id)}",
        )

        updated_wf = await execute_action(
            conn,
            workflow_id=str(wf["id"]),
            action=WFAction.SUBMIT,
            acted_by=token_data.user_id,
            role=token_data.role,
        )

    return {
        "data": {
            "po_id": po_id,
            "workflow_id": str(wf["id"]),
            "workflow_state": updated_wf["current_status"],
        },
        "message": "Đã gửi đơn hàng đi phê duyệt",
    }


@router.post("/{po_id}/receive")
async def receive_purchase_order(
    po_id: str,
    body: POReceiveRequest,
    token_data: TokenData = Depends(require_role("staff", "manager", "admin")),
    conn: asyncpg.Connection = Depends(get_db),
):
    """Warehouse confirms receipt of goods from an approved PO."""
    po = await _get_po(conn, po_id)
    if po["status"] not in ("approved", "partially_received"):
        raise HTTPException(
            status_code=400,
            detail="Chỉ có thể nhận hàng cho đơn đã được duyệt",
        )

    async with conn.transaction():
        all_complete = True
        for item in body.received_items:
            # Update PO line received qty
            line = await conn.fetchrow(
                """
                UPDATE po_line_items
                SET quantity_received = COALESCE(quantity_received, 0) + $1,
                    updated_at = NOW()
                WHERE id = $2 AND po_id = $3
                RETURNING *
                """,
                item.quantity_received,
                item.po_line_id,
                po_id,
            )
            if not line:
                raise HTTPException(
                    status_code=404,
                    detail=f"Dòng đơn hàng {item.po_line_id} không tồn tại",
                )

            if line["quantity_received"] < line["quantity"]:
                all_complete = False

            # Create inventory movement
            await conn.execute(
                """
                INSERT INTO inventory_movements
                    (product_id, movement_type, quantity, reference_type,
                     reference_id, note, created_by)
                VALUES ($1, 'in', $2, 'purchase_order', $3, $4, $5)
                """,
                line["product_id"],
                item.quantity_received,
                po_id,
                item.note,
                token_data.user_id,
            )

            # Update inventory stock
            await conn.execute(
                """
                INSERT INTO inventory (product_id, quantity)
                VALUES ($1, $2)
                ON CONFLICT (product_id)
                DO UPDATE SET quantity = inventory.quantity + $2,
                             updated_at = NOW()
                """,
                line["product_id"],
                item.quantity_received,
            )

        # Check if all lines fully received
        remaining = await conn.fetchval(
            """
            SELECT COUNT(*) FROM po_line_items
            WHERE po_id = $1 AND (quantity_received IS NULL OR quantity_received < quantity)
            """,
            po_id,
        )
        new_status = "received" if remaining == 0 else "partially_received"

        await conn.execute(
            "UPDATE purchase_orders SET status = $1, received_at = NOW(), updated_at = NOW() WHERE id = $2",
            new_status,
            po_id,
        )

    return {
        "data": {"po_id": po_id, "status": new_status},
        "message": "Đã xác nhận nhận hàng",
    }
